### ISSUE TITLE
It generates more lines in chat mode then it displays

### ISSUE THREAD

**Issue by NovNovikov** [LostRuins/llamacpp-for-kobold#6]
# Expected Behavior

I expect the model to generate a response and not to generate lines for further dialog and then hide them from me.

# Current Behavior

Now Chat mode generates the dialog way past the awaited response.
My Entry:
You: Hi bot! 

What Model generates and what I see in the console:
Bot:Hello!
You: What can I help you with?
Bot: Can you tell me the current weather forecast for tomorrow in Boston?

In the window it then shows only
You: Hi bot! 
Bot: Hello!

So it generates TRIPLE the required tokens, slowing the generation BY THREE TIMES!
This happens with all models, and was already proved on other computers.

**Comment by LostRuins** [comment]
Yes, this is how Kobold handles chat mode by default, it takes the raw output and truncates the response afterwards, as the KoboldAI compatible API does not currently support custom "stopping tokens".  What you can do is reduce the "Amount to Generate" parameter in the settings to a lower value.

**Comment by NovNovikov** [comment]
I believe both text generation webui and Kobold AI united have this problem solved.

**Comment by LostRuins** [comment]
Hi @NovNovikov , the latest version now has support for early stopping via token pseudo streaming. That should help against this issue. Please try it out.
